name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Update README
      run: |-
        ./gradlew run --args="-o README.md"
        cat README.md
    - name: (Fail-only) Upload the build report
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: error-report
        path: build-reports.zip
